
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract toDoList {
    // Contract can have an instance variables.
    // In this example instance variable `timestamp` is used to store the time of `constructor` or `touch`
    // function call
    uint32 public timestamp;
    struct task {
        string name;
        uint32 taskTime;
        bool flag;
    }
    mapping  (uint => task) public assoc;
    string[] public nameArr;
    // Contract can have a `constructor` – function that will be called when contract will be deployed to the blockchain.
    // In this example constructor adds current time to the instance variable.
    // All contracts need call tvm.accept(); for succeeded deploy
    constructor() public {
        // Check that contract's public key is set
        require(tvm.pubkey() != 0, 101);
        // Check that message has signature (msg.pubkey() is not zero) and
        // message is signed with the owner's private key
        require(msg.pubkey() == tvm.pubkey(), 102);
        // The current smart contract agrees to buy some gas to finish the
        // current transaction. This actions required to process external
        // messages, which bring no value (henceno gas) with themselves.
        tvm.accept();

        timestamp = now;
    }

     modifier checkOwnerAndAccept {
		// Check that message was signed with contracts key.
		require(msg.pubkey() == tvm.pubkey(), 102);
		tvm.accept();
		_;
	}
    function addTask (string name, bool flagTask) public checkOwnerAndAccept{
        uint32 newTaskTime = now;
        nameArr.push(name);
        uint taskKey = nameArr.length;
        assoc[taskKey].name = name;
        assoc[taskKey].taskTime = newTaskTime;
        assoc[taskKey].flag = flagTask;
    }
    function getOpenTasks () public checkOwnerAndAccept returns(uint8) {
       uint8 count = 0;
       for (uint8 i = 1; i <= nameArr.length; i++){
           if (!assoc[i].flag) {
               count++;
           }
       }
       return count;
    }
    function getTaskList () public checkOwnerAndAccept returns(string[]) {
        return nameArr;
    }
    function getTaskDescription(uint8 key) public checkOwnerAndAccept returns(string, uint32, bool) {
        require(key > 0 && key <= nameArr.length);
        return (assoc[key].name,
        assoc[key].taskTime,
        assoc[key].flag);
    }
    function deleteTask(uint8 key) public checkOwnerAndAccept {
        require(key > 0 && key <= nameArr.length);
        delete assoc[key].name;
        delete assoc[key].taskTime;
        delete assoc[key];
        delete nameArr[key];
    }
    function taskDone(uint8 key) public checkOwnerAndAccept {
        require(key > 0 && key <= nameArr.length);
        require(!assoc[key].flag);
        assoc[key].flag = true;
    }
}
