
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
import 'Structs.sol';
// This is class that describes you smart contract.
interface IShoppingList {
    function getShoppingStat() external returns (shoppingSummary summary);
    function addPurchase(string name, uint32 number) external ;
    function deletePurchase(uint32 purchaseID) external;
    function buy(uint32 purchaseID, uint32 priceForAll) external;
    function getShoppingList() external returns (purchase[] purchasesArray);
}

interface Transactable {
    function sendTransaction(address dest, uint128 value, bool bounce, uint8 flags, TvmCell payload  ) external;
}