
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
import 'WarUnit.sol';
// This is class that describes you smart contract.
contract Archer is WarUnit {
    constructor(gamingObject BaseStationAddress) public {
        address WarUnitAddress = address(this);
        BaseStationAddress.addWarUnit(WarUnitAddress);
        UnitBaseStation = BaseStationAddress;
        HP = 15;
        attackPower = 3;
    }
}